"""
NQ Signal Pro — FastAPI Backend

Entrypoint for the Render-hosted service. Responsibilities:
  • Receive TradingView webhook alerts  → store signals, open paper trades
  • Expose REST API for Squarespace widgets
  • Run a background scheduler to:
      - resolve open paper trades against real price data
      - run the Python signal engines (optional, independent of TradingView)
      - generate optimization insights
  • Health check endpoint for Render monitoring
"""

from __future__ import annotations

import logging
import sys
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone

import uvicorn
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .database import Base, SessionLocal, engine
from .models import Signal, PaperTrade, StrategyLog  # ensure tables are created
from .routers import signals, webhook, performance

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=getattr(logging, settings.log_level.upper(), logging.INFO),
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)

scheduler = AsyncIOScheduler()


# ── Lifespan (startup / shutdown) ─────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting NQ Signal Pro backend …")

    # Create all tables on startup (idempotent)
    Base.metadata.create_all(bind=engine)
    logger.info("Database tables ready.")

    # Start background scheduler
    scheduler.add_job(
        _resolve_paper_trades_job,
        "interval",
        minutes=5,
        id="resolve_trades",
        replace_existing=True,
    )
    scheduler.add_job(
        _optimization_loop_job,
        "cron",
        hour=4,
        minute=0,           # 4 AM UTC daily — after US session closes
        id="optimization_loop",
        replace_existing=True,
    )
    scheduler.start()
    logger.info("Scheduler started.")

    yield

    scheduler.shutdown(wait=False)
    logger.info("Scheduler stopped.")


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="NQ Signal Pro API",
    description=(
        "Backend for MNQ and MGC futures signal tracking, paper trading, "
        "and performance analytics. Signals are generated by TradingView "
        "Pine Scripts and received via webhook."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — allow Squarespace to call the API
origins = [o.strip() for o in settings.cors_origins.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# Routers
app.include_router(webhook.router)
app.include_router(signals.router)
app.include_router(performance.router)


# ── Core endpoints ────────────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root():
    return {"service": "NQ Signal Pro", "status": "running", "docs": "/docs"}


@app.get("/health", tags=["Health"])
def health_check():
    """Render uses this to verify the service is alive."""
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


# ── Background jobs ───────────────────────────────────────────────────────────

async def _resolve_paper_trades_job():
    """
    Every 5 minutes: fetch recent OHLCV and resolve any open paper trades.
    Uses yfinance as the data source (free, no API key needed).
    """
    try:
        import yfinance as yf
        from .services.paper_trading import resolve_open_trades

        db = SessionLocal()
        try:
            for instrument, ticker in [("MGC", "GC=F"), ("MNQ", "NQ=F")]:
                open_count = (
                    db.query(PaperTrade)
                    .filter(PaperTrade.instrument == instrument, PaperTrade.status == "OPEN")
                    .count()
                )
                if open_count == 0:
                    continue

                # Fetch last 2 days of 5-minute bars
                df = yf.download(ticker, period="2d", interval="5m", progress=False)
                if df.empty:
                    continue

                df.columns = [c.lower() for c in df.columns]
                df.index = df.index.tz_convert("UTC")

                closed = resolve_open_trades(db, df, instrument)
                if closed:
                    logger.info(
                        "Resolved %d paper trades for %s", len(closed), instrument
                    )
        finally:
            db.close()
    except Exception as exc:
        logger.error("Error in resolve_paper_trades_job: %s", exc, exc_info=True)


async def _optimization_loop_job():
    """
    Daily: analyse performance and write insights to StrategyLog.

    NEVER auto-applies changes — only records findings for human review.
    """
    try:
        from .services.paper_trading import compute_performance_stats

        db = SessionLocal()
        try:
            for instrument in ("MGC", "MNQ"):
                stats = compute_performance_stats(db, instrument)
                if stats["total_trades"] < 5:
                    continue

                insights = _generate_insights(stats, instrument)
                for msg, data in insights:
                    log = StrategyLog(
                        instrument=instrument,
                        log_type="INSIGHT",
                        message=msg,
                        data_json=__import__("json").dumps(data),
                    )
                    db.add(log)
            db.commit()
            logger.info("Optimization loop complete.")
        finally:
            db.close()
    except Exception as exc:
        logger.error("Error in optimization_loop_job: %s", exc, exc_info=True)


def _generate_insights(stats: dict, instrument: str) -> list[tuple[str, dict]]:
    """
    Produce human-readable insights from performance stats.
    Returns list of (message, supporting_data) tuples.
    """
    insights = []

    wr = stats["win_rate"]
    if wr < 45:
        insights.append((
            f"{instrument}: Win rate has dropped to {wr:.1f}% over "
            f"{stats['total_trades']} trades. Consider reviewing gate thresholds "
            "or reducing position size until performance improves.",
            {"win_rate": wr, "trades": stats["total_trades"]},
        ))
    elif wr >= 70:
        insights.append((
            f"{instrument}: Strong performance — {wr:.1f}% win rate over "
            f"{stats['total_trades']} trades.",
            {"win_rate": wr, "trades": stats["total_trades"]},
        ))

    if stats["best_setup"]:
        best_wr = stats["setup_win_rates"].get(stats["best_setup"], 0)
        insights.append((
            f"{instrument}: Best-performing setup is '{stats['best_setup']}' "
            f"with {best_wr:.1f}% win rate. Consider prioritising A+ grade signals "
            "from this setup.",
            {"best_setup": stats["best_setup"], "best_wr": best_wr},
        ))

    if stats["worst_setup"]:
        worst_wr = stats["setup_win_rates"].get(stats["worst_setup"], 0)
        if worst_wr < 40:
            insights.append((
                f"{instrument}: Weakest setup is '{stats['worst_setup']}' "
                f"({worst_wr:.1f}% win rate). Consider disabling or raising the grade "
                "threshold for this setup type.",
                {"worst_setup": stats["worst_setup"], "worst_wr": worst_wr},
            ))

    pf = stats.get("profit_factor")
    if pf is not None and pf < 1.0:
        insights.append((
            f"{instrument}: Profit factor is below 1.0 ({pf:.2f}). "
            "The strategy is currently losing more than it wins in dollar terms. "
            "PAUSE paper trading and review recent signals before continuing.",
            {"profit_factor": pf},
        ))

    return insights


# ── Dev server ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)
