"""
NQ Signal Pro — FastAPI Backend

Entrypoint for the Render-hosted service. Responsibilities:
  • Receive TradingView webhook alerts  → store signals, open paper trades
  • Expose REST API for Squarespace widgets
  • Run a background scheduler to:
      - resolve open paper trades against real price data
      - run the Python signal engines (optional, independent of TradingView)
      - generate optimization insights
  • Health check endpoint for Render monitoring
"""

from __future__ import annotations

import logging
import sys
from contextlib import asynccontextmanager
from datetime import datetime, timedelta, timezone

import uvicorn
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .database import Base, SessionLocal, engine
from .models import Signal, PaperTrade, StrategyLog  # ensure tables are created
from .routers import signals, webhook, performance

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=getattr(logging, settings.log_level.upper(), logging.INFO),
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)

scheduler = AsyncIOScheduler()


# ── Lifespan (startup / shutdown) ─────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting NQ Signal Pro backend …")

    # Create all tables on startup (idempotent)
    Base.metadata.create_all(bind=engine)
    logger.info("Database tables ready.")

    # Start background scheduler
    scheduler.add_job(
        _resolve_paper_trades_job,
        "interval",
        minutes=5,
        id="resolve_trades",
        replace_existing=True,
    )
    scheduler.add_job(
        _optimization_loop_job,
        "cron",
        hour=4,
        minute=0,
        id="optimization_loop",
        replace_existing=True,
    )
    scheduler.add_job(
        _daily_reset_job,
        "cron",
        hour=0,
        minute=1,           # just after midnight UTC — reset daily counters
        id="daily_reset",
        replace_existing=True,
    )
    scheduler.start()
    logger.info("Scheduler started.")

    yield

    scheduler.shutdown(wait=False)
    logger.info("Scheduler stopped.")


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="NQ Signal Pro API",
    description=(
        "Backend for MNQ and MGC futures signal tracking, paper trading, "
        "and performance analytics. Signals are generated by TradingView "
        "Pine Scripts and received via webhook."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — allow Squarespace to call the API
origins = [o.strip() for o in settings.cors_origins.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# Routers
app.include_router(webhook.router)
app.include_router(signals.router)
app.include_router(performance.router)


# ── Core endpoints ────────────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
def root():
    return {"service": "NQ Signal Pro", "status": "running", "docs": "/docs"}


@app.get("/health", tags=["Health"])
def health_check():
    """Render uses this to verify the service is alive."""
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


# ── Background jobs ───────────────────────────────────────────────────────────

async def _resolve_paper_trades_job():
    """
    Every 5 minutes: fetch recent OHLCV and resolve any open paper trades.
    Uses yfinance as the data source (free, no API key needed).
    """
    try:
        import yfinance as yf
        from .services.paper_trading import resolve_open_trades

        db = SessionLocal()
        try:
            for instrument, ticker in [("MGC", "GC=F"), ("MNQ", "NQ=F")]:
                open_count = (
                    db.query(PaperTrade)
                    .filter(PaperTrade.instrument == instrument, PaperTrade.status == "OPEN")
                    .count()
                )
                if open_count == 0:
                    continue

                # Fetch last 2 days of 5-minute bars
                df = yf.download(ticker, period="2d", interval="5m", progress=False)
                if df.empty:
                    continue

                df.columns = [c.lower() for c in df.columns]
                df.index = df.index.tz_convert("UTC")

                closed = resolve_open_trades(db, df, instrument)
                if closed:
                    logger.info(
                        "Resolved %d paper trades for %s", len(closed), instrument
                    )
        finally:
            db.close()
    except Exception as exc:
        logger.error("Error in resolve_paper_trades_job: %s", exc, exc_info=True)


async def _daily_reset_job():
    """Midnight UTC: create fresh DailyStats rows so counters start at zero each day."""
    try:
        from .services.paper_trading import reset_daily_stats
        db = SessionLocal()
        try:
            reset_daily_stats(db)
        finally:
            db.close()
    except Exception as exc:
        logger.error("Error in daily_reset_job: %s", exc, exc_info=True)


async def _optimization_loop_job():
    """
    Daily at 4 AM UTC: analyse performance and write insights to StrategyLog.

    The self-learning loop looks at:
      • Overall win rate trend (last 10 vs all-time)
      • Per-setup win rates — flag declining setups
      • Best/worst trading sessions
      • Profit factor and drawdown patterns
      • Ticks P&L trajectory

    NEVER auto-applies changes — only records findings for human review.
    """
    try:
        import json as _json
        from .services.paper_trading import compute_performance_stats
        from .models import PaperTrade, DailyStats
        from datetime import date, timedelta

        db = SessionLocal()
        try:
            for instrument in ("MGC", "MNQ"):
                stats = compute_performance_stats(db, instrument)
                if stats["total_trades"] < 5:
                    continue

                insights = _generate_insights(stats, instrument, db)
                for msg, log_type, data in insights:
                    log = StrategyLog(
                        instrument=instrument,
                        log_type=log_type,
                        message=msg,
                        data_json=_json.dumps(data),
                    )
                    db.add(log)
            db.commit()
            logger.info("Optimization loop complete.")
        finally:
            db.close()
    except Exception as exc:
        logger.error("Error in optimization_loop_job: %s", exc, exc_info=True)


def _generate_insights(stats: dict, instrument: str, db) -> list[tuple[str, str, dict]]:
    """
    Returns list of (message, log_type, data) tuples.
    log_type: INSIGHT | WARNING | SUGGESTION
    """
    import json as _json
    from datetime import date, timedelta
    from .models import PaperTrade, DailyStats, Signal as SignalModel

    insights = []
    wr = stats["win_rate"]
    total = stats["total_trades"]
    pf = stats.get("profit_factor")
    total_ticks = stats.get("total_ticks", 0)

    # ── Win rate assessment ────────────────────────────────────────────────────
    if wr < 45:
        insights.append((
            f"{instrument}: Win rate {wr:.1f}% over {total} trades is below 45% threshold. "
            "Review gate thresholds or raise minimum grade to A+.",
            "WARNING",
            {"win_rate": wr, "trades": total},
        ))
    elif wr >= 65:
        insights.append((
            f"{instrument}: Strong win rate of {wr:.1f}% over {total} trades.",
            "INSIGHT",
            {"win_rate": wr, "trades": total},
        ))

    # ── Recent trend: last 10 trades vs all-time ───────────────────────────────
    recent = (
        db.query(PaperTrade)
        .filter(PaperTrade.instrument == instrument, PaperTrade.status == "CLOSED")
        .order_by(PaperTrade.closed_at.desc())
        .limit(10)
        .all()
    )
    if len(recent) >= 10:
        recent_wins = sum(1 for t in recent if t.is_win)
        recent_wr = recent_wins / len(recent) * 100
        if recent_wr < wr - 15:
            insights.append((
                f"{instrument}: Last 10 trades show declining performance — "
                f"{recent_wr:.0f}% win rate vs {wr:.1f}% all-time. "
                "Consider pausing until conditions improve.",
                "WARNING",
                {"recent_wr": recent_wr, "alltime_wr": wr},
            ))
        elif recent_wr > wr + 15:
            insights.append((
                f"{instrument}: Recent momentum improving — "
                f"last 10 trades at {recent_wr:.0f}% vs {wr:.1f}% all-time.",
                "INSIGHT",
                {"recent_wr": recent_wr, "alltime_wr": wr},
            ))

    # ── Setup analysis ─────────────────────────────────────────────────────────
    if stats["best_setup"]:
        best_wr = stats["setup_win_rates"].get(stats["best_setup"], 0)
        insights.append((
            f"{instrument}: Best setup is '{stats['best_setup']}' at {best_wr:.1f}% win rate. "
            "Prioritise A+ signals from this setup.",
            "SUGGESTION",
            {"best_setup": stats["best_setup"], "best_wr": best_wr},
        ))

    if stats["worst_setup"]:
        worst_wr = stats["setup_win_rates"].get(stats["worst_setup"], 0)
        if worst_wr < 40:
            insights.append((
                f"{instrument}: '{stats['worst_setup']}' is underperforming at {worst_wr:.1f}%. "
                "Consider disabling this setup or requiring A+ grade only.",
                "SUGGESTION",
                {"worst_setup": stats["worst_setup"], "worst_wr": worst_wr},
            ))

    # ── Profit factor ──────────────────────────────────────────────────────────
    if pf is not None and pf < 1.0:
        insights.append((
            f"{instrument}: Profit factor {pf:.2f} is below 1.0 — "
            "losing more than winning in dollar terms. PAUSE and review.",
            "WARNING",
            {"profit_factor": pf},
        ))
    elif pf is not None and pf >= 2.0:
        insights.append((
            f"{instrument}: Excellent profit factor of {pf:.2f}.",
            "INSIGHT",
            {"profit_factor": pf},
        ))

    # ── Ticks P&L trajectory ──────────────────────────────────────────────────
    if total_ticks < 0:
        insights.append((
            f"{instrument}: Cumulative P&L is negative ({total_ticks:+.0f} ticks). "
            "Review entries — consider requiring higher score threshold.",
            "WARNING",
            {"total_ticks": total_ticks},
        ))

    # ── Session-based learning: last 30 days ──────────────────────────────────
    try:
        import pytz
        ET = pytz.timezone("America/New_York")
        from collections import defaultdict
        session_data: dict = defaultdict(lambda: {"wins": 0, "total": 0})

        all_closed = (
            db.query(PaperTrade)
            .filter(PaperTrade.instrument == instrument, PaperTrade.status == "CLOSED")
            .all()
        )
        for t in all_closed:
            if not t.opened_at:
                continue
            et = t.opened_at.astimezone(ET) if t.opened_at.tzinfo else ET.localize(t.opened_at)
            h = et.hour
            sess = "London" if 2 <= h < 8 else "NY Open" if 8 <= h < 12 else "Afternoon" if 13 <= h < 17 else "Other"
            session_data[sess]["total"] += 1
            if t.is_win:
                session_data[sess]["wins"] += 1

        best_sess = max(
            ((s, v) for s, v in session_data.items() if v["total"] >= 5),
            key=lambda x: x[1]["wins"] / x[1]["total"],
            default=None,
        )
        worst_sess = min(
            ((s, v) for s, v in session_data.items() if v["total"] >= 5),
            key=lambda x: x[1]["wins"] / x[1]["total"],
            default=None,
        )
        if best_sess:
            s, v = best_sess
            sess_wr = v["wins"] / v["total"] * 100
            insights.append((
                f"{instrument}: Best session is '{s}' with {sess_wr:.0f}% win rate "
                f"over {v['total']} trades. Focus signals during this window.",
                "SUGGESTION",
                {"best_session": s, "session_wr": round(sess_wr, 1), "session_trades": v["total"]},
            ))
        if worst_sess and worst_sess[1]["wins"] / worst_sess[1]["total"] < 0.4:
            s, v = worst_sess
            sess_wr = v["wins"] / v["total"] * 100
            insights.append((
                f"{instrument}: Weakest session is '{s}' at {sess_wr:.0f}% win rate. "
                "Consider filtering out signals during this window.",
                "SUGGESTION",
                {"worst_session": s, "session_wr": round(sess_wr, 1)},
            ))
    except Exception:
        pass

    return insights


# ── Dev server ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)
