from sqlalchemy import Column, Integer, Float, String, Boolean, DateTime, Date, Text, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from datetime import datetime

from .database import Base


class Signal(Base):
    """Every trade signal — generated by the autonomous Python engine."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(10), nullable=False, index=True)  # MGC | MNQ
    direction = Column(String(10), nullable=False)               # LONG | SHORT
    setup_type = Column(String(20))   # OTE_PULLBACK | STDV_REVERSAL | OTE+STDV
    grade = Column(String(5))         # A+ | A
    score = Column(Float)

    entry_price = Column(Float, nullable=False)
    sl_price = Column(Float, nullable=False)
    tp1_price = Column(Float, nullable=False)
    tp2_price = Column(Float)
    tp3_price = Column(Float)
    tp4_price = Column(Float)

    # JSON snapshot of factor states at signal time
    gates_json = Column(Text)

    signal_time = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    # ENGINE = autonomous Python engine | TRADINGVIEW = manual webhook override
    source = Column(String(20), default="ENGINE")

    paper_trades = relationship(
        "PaperTrade", back_populates="signal", cascade="all, delete-orphan"
    )


class PaperTrade(Base):
    """Simulated trade opened when a signal fires. Resolved against real OHLCV data."""
    __tablename__ = "paper_trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=False)
    instrument = Column(String(10), nullable=False, index=True)
    direction = Column(String(10), nullable=False)

    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)
    # TP1 | TP2 | TP3 | TP4 | SL | BE | EXPIRED
    exit_reason = Column(String(20))

    contracts = Column(Integer, default=1)
    pnl_points = Column(Float)
    pnl_ticks = Column(Float)
    pnl_dollars = Column(Float)

    opened_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    closed_at = Column(DateTime)
    breakeven_moved = Column(Boolean, default=False)

    status = Column(String(20), default="OPEN", index=True)

    signal = relationship("Signal", back_populates="paper_trades")

    @property
    def is_win(self) -> bool:
        return self.exit_reason in ("TP1", "TP2", "TP3", "TP4")

    @property
    def is_be(self) -> bool:
        return self.exit_reason == "BE"


class DailyStats(Base):
    """Per-instrument daily counters and risk state."""
    __tablename__ = "daily_stats"
    __table_args__ = (UniqueConstraint("instrument", "date", name="uq_instrument_date"),)

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(10), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)

    trades_count = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    be_count = Column(Integer, default=0)
    pnl_ticks = Column(Float, default=0.0)
    pnl_dollars = Column(Float, default=0.0)
    consecutive_losses = Column(Integer, default=0)
    is_halted = Column(Boolean, default=False)
    halt_reason = Column(String(50))


class StrategyLog(Base):
    """Learning loop output: insights, warnings, parameter suggestions."""
    __tablename__ = "strategy_logs"

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(10))
    # INSIGHT | SUGGESTION | WARNING | PARAM_UPDATE
    log_type = Column(String(30))
    message = Column(Text, nullable=False)
    data_json = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    applied = Column(Boolean, default=False)


class EngineParams(Base):
    """
    Adaptive engine parameters written by the optimization loop.
    Every parameter change creates a new row (full audit trail).
    The engine always loads the most recent row at scan time.
    """
    __tablename__ = "engine_params"

    id = Column(Integer, primary_key=True, index=True)
    instrument = Column(String(10), nullable=False, index=True)
    params_json = Column(Text, nullable=False)  # JSON dict of MNQEngine kwargs
    version = Column(Integer, default=1)
    reason = Column(Text)    # human-readable explanation for the change
    updated_at = Column(DateTime, default=datetime.utcnow)
